/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search artists (MusicBrainz) */
        get: operations["searchArtists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover albums from a natural-language listening request */
        post: operations["discoverAlbums"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/request": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Request a magic-link sign-in email
         * @description Accepts an email address and, if login is configured (RESEND_API_KEY
         *     set), emails a time-limited sign-in link. The response is the same
         *     whether or not the address already has an account — accounts are
         *     created lazily on first successful GET /auth/verify — so this
         *     endpoint cannot be used to enumerate registered emails.
         */
        post: operations["requestLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Render a non-destructive sign-in confirmation page
         * @description Renders an HTML page with a form that POSTs back to this same
         *     endpoint. Deliberately does not consume the token itself: email
         *     security scanners and prefetchers (e.g. Microsoft Defender
         *     SafeLinks, Proofpoint) automatically fetch links found in incoming
         *     mail before the recipient opens the message, and a GET that
         *     consumed the one-time token would let that automated fetch burn it
         *     before the real user ever clicks. Only the POST below (the form's
         *     own submission, which scanners don't perform) actually completes
         *     sign-in. The response is never cached (`Cache-Control: no-store`).
         */
        get: operations["verifyLoginConfirm"];
        put?: never;
        /**
         * Consume a magic-link token and start a session
         * @description Submitted by the confirmation page's own form (GET /auth/verify
         *     above). Consumes the one-time token, delivered as an HttpOnly
         *     `freqshow_session` cookie, then either redirects to the configured
         *     frontend URL or serves a minimal confirmation page. The response
         *     is never cached (`Cache-Control: no-store`).
         */
        post: operations["verifyLogin"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get the current authenticated user
         * @description Returns the user record associated with the caller's session cookie.
         *     Returns 401 if unauthenticated, missing, or expired.
         */
        get: operations["getAuthMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Terminate the current session and clear session cookie
         * @description Deletes the session behind the caller's session cookie and clears the cookie.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get artist by MusicBrainz ID (cache-first) */
        get: operations["getArtist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get album (release group) by MusicBrainz ID (cache-first) */
        get: operations["getAlbum"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            status: string;
        };
        ErrorResponse: {
            error: string;
        };
        /** @description MusicBrainz artist search results */
        SearchResult: {
            artists: components["schemas"]["SearchArtist"][];
            offset: number;
            count: number;
        };
        SearchArtist: {
            id: string;
            name: string;
            country?: string | null;
            type?: string | null;
            disambiguation?: string | null;
            aliases?: string[];
            lifeSpan: components["schemas"]["LifeSpan"];
        };
        AuthRequestBody: {
            /** Format: email */
            email: string;
        };
        AuthRequestResponse: {
            status: string;
            message?: string;
        };
        AuthLogoutResponse: {
            status: string;
            message?: string;
        };
        User: {
            id: string;
            /** Format: email */
            email: string;
            /** Format: date-time */
            createdAt: string;
        };
        DiscoveryQuery: {
            query: string;
            alreadyKnown?: string[];
        };
        InterpretedQuery: {
            mood: string;
            eraHints: string[];
            sonicQualities: string[];
            referenceArtists: string[];
            avoid: string[];
            /** @enum {string} */
            discoveryAppetite: "low" | "medium" | "high";
        };
        DiscoveryPick: {
            rank: number;
            albumId: string;
            title: string;
            artistName: string;
            year: number;
            whyItFits: string;
            whatToListenFor: string;
            spotifySearchUrl: string;
        };
        DiscoveryResult: {
            interpreted: components["schemas"]["InterpretedQuery"];
            picks: components["schemas"]["DiscoveryPick"][];
        };
        Artist: {
            id: string;
            name: string;
            biography: string;
            /** @description Canonical Wikipedia page URL when the biography was sourced from Wikipedia. */
            biographyUrl?: string;
            genres: string[];
            albums: components["schemas"]["Album"][];
            related: components["schemas"]["RelatedArtist"][];
            imageUrl: string;
            country?: string | null;
            type?: string | null;
            disambiguation?: string | null;
            aliases?: string[];
            lifeSpan: components["schemas"]["LifeSpan"];
        };
        RelatedArtist: {
            id: string;
            name: string;
            /** @description MusicBrainz relation type connecting this artist to the current artist. */
            relationshipType?: string;
        };
        LifeSpan: {
            begin?: string | null;
            end?: string | null;
            ended?: boolean | null;
        };
        Album: {
            id: string;
            title: string;
            artistId: string;
            artistName?: string | null;
            primaryType?: string | null;
            secondaryTypes?: string[];
            firstReleaseDate?: string | null;
            /** @description Release year extracted from firstReleaseDate when available */
            year: number;
            genre: string;
            label: string;
            tracks: components["schemas"]["Track"][];
            review: components["schemas"]["Review"];
            coverUrl: string;
        };
        Track: {
            number: number;
            title: string;
            /** @description Track duration formatted as MM:SS */
            length: string;
        };
        Review: {
            source: string;
            author: string;
            /** Format: double */
            rating: number;
            summary: string;
            text: string;
            url: string;
        };
    };
    responses: {
        /** @description Method not allowed */
        MethodNotAllowed: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        /** @description MusicBrainz artist MBID */
        ArtistId: string;
        /** @description MusicBrainz release-group MBID */
        AlbumId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    searchArtists: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                /**
                 * @description Maximum number of results to return.
                 *
                 *     Implementation defaults to 25 and clamps to 1..100.
                 */
                limit?: number;
                /**
                 * @description Result offset for pagination.
                 *
                 *     Implementation defaults to 0.
                 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description Missing/invalid query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            /** @description Search failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    discoverAlbums: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoveryQuery"];
            };
        };
        responses: {
            /** @description Discovery recommendations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryResult"];
                };
            };
            /** @description Invalid request body or query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            /** @description Discovery provider failure or invalid LLM output */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Discovery unavailable or index not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    requestLogin: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AuthRequestBody"];
            };
        };
        responses: {
            /** @description Sign-in email sent (or accepted for sending) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthRequestResponse"];
                };
            };
            /** @description Invalid request body or malformed email address */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            /** @description Too many login requests from this client */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Login is not configured (no Resend API key) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    verifyLoginConfirm: {
        parameters: {
            query: {
                /** @description The one-time token from the emailed sign-in link */
                token: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Confirmation page served; token has not been consumed */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Missing token query parameter */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Login is not configured (no Resend API key) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    verifyLogin: {
        parameters: {
            query?: {
                /** @description The one-time token, when not supplied as a form field (see requestBody) — accepted either way for robustness. */
                token?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/x-www-form-urlencoded": {
                    token?: string;
                };
            };
        };
        responses: {
            /** @description Signed in; session cookie set; confirmation page served */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/html": string;
                };
            };
            /** @description Signed in; session cookie set; redirected to the configured frontend URL */
            303: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing token (query parameter or form field) */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Token is invalid, expired, or already used */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            /** @description Login is not configured (no Resend API key) */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAuthMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated user details */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            /** @description Not authenticated or session expired */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successfully signed out */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthLogoutResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    getArtist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MusicBrainz artist MBID */
                id: components["parameters"]["ArtistId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artist"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Artist not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            /** @description Upstream error (MusicBrainz) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dependency unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAlbum: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MusicBrainz release-group MBID */
                id: components["parameters"]["AlbumId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Album */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Album"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Album not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            /** @description Upstream error (MusicBrainz) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dependency unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
