/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health check */
        get: operations["healthz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Search artists (MusicBrainz) */
        get: operations["searchArtists"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/discover": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Discover albums from a natural-language listening request */
        post: operations["discoverAlbums"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/artists/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get artist by MusicBrainz ID (cache-first) */
        get: operations["getArtist"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/albums/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get album (release group) by MusicBrainz ID (cache-first) */
        get: operations["getAlbum"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        HealthResponse: {
            status: string;
        };
        ErrorResponse: {
            error: string;
        };
        /** @description MusicBrainz artist search results */
        SearchResult: {
            artists: components["schemas"]["SearchArtist"][];
            offset: number;
            count: number;
        };
        SearchArtist: {
            id: string;
            name: string;
            country?: string | null;
            type?: string | null;
            disambiguation?: string | null;
            aliases?: string[];
            lifeSpan: components["schemas"]["LifeSpan"];
        };
        DiscoveryQuery: {
            query: string;
            alreadyKnown?: string[];
        };
        InterpretedQuery: {
            mood: string;
            eraHints: string[];
            sonicQualities: string[];
            referenceArtists: string[];
            avoid: string[];
            /** @enum {string} */
            discoveryAppetite: "low" | "medium" | "high";
        };
        DiscoveryPick: {
            rank: number;
            albumId: string;
            title: string;
            artistName: string;
            year: number;
            whyItFits: string;
            whatToListenFor: string;
            spotifySearchUrl: string;
        };
        DiscoveryResult: {
            interpreted: components["schemas"]["InterpretedQuery"];
            picks: components["schemas"]["DiscoveryPick"][];
        };
        Artist: {
            id: string;
            name: string;
            biography: string;
            /** @description Canonical Wikipedia page URL when the biography was sourced from Wikipedia. */
            biographyUrl?: string;
            genres: string[];
            albums: components["schemas"]["Album"][];
            related: components["schemas"]["RelatedArtist"][];
            imageUrl: string;
            country?: string | null;
            type?: string | null;
            disambiguation?: string | null;
            aliases?: string[];
            lifeSpan: components["schemas"]["LifeSpan"];
        };
        RelatedArtist: {
            id: string;
            name: string;
            /** @description MusicBrainz relation type connecting this artist to the current artist. */
            relationshipType?: string;
        };
        LifeSpan: {
            begin?: string | null;
            end?: string | null;
            ended?: boolean | null;
        };
        Album: {
            id: string;
            title: string;
            artistId: string;
            artistName?: string | null;
            primaryType?: string | null;
            secondaryTypes?: string[];
            firstReleaseDate?: string | null;
            /** @description Release year extracted from firstReleaseDate when available */
            year: number;
            genre: string;
            label: string;
            tracks: components["schemas"]["Track"][];
            review: components["schemas"]["Review"];
            coverUrl: string;
        };
        Track: {
            number: number;
            title: string;
            /** @description Track duration formatted as MM:SS */
            length: string;
        };
        Review: {
            source: string;
            author: string;
            /** Format: double */
            rating: number;
            summary: string;
            text: string;
            url: string;
        };
    };
    responses: {
        /** @description Method not allowed */
        MethodNotAllowed: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
    };
    parameters: {
        /** @description MusicBrainz artist MBID */
        ArtistId: string;
        /** @description MusicBrainz release-group MBID */
        AlbumId: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    healthz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
        };
    };
    searchArtists: {
        parameters: {
            query: {
                /** @description Search query */
                q: string;
                /**
                 * @description Maximum number of results to return.
                 *
                 *     Implementation defaults to 25 and clamps to 1..100.
                 */
                limit?: number;
                /**
                 * @description Result offset for pagination.
                 *
                 *     Implementation defaults to 0.
                 */
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Search results */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResult"];
                };
            };
            /** @description Missing/invalid query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            /** @description Search failed */
            500: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    discoverAlbums: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DiscoveryQuery"];
            };
        };
        responses: {
            /** @description Discovery recommendations */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DiscoveryResult"];
                };
            };
            /** @description Invalid request body or query */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            /** @description Discovery provider failure or invalid LLM output */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Discovery unavailable or index not ready */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getArtist: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MusicBrainz artist MBID */
                id: components["parameters"]["ArtistId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Artist */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Artist"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Artist not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            /** @description Upstream error (MusicBrainz) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dependency unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAlbum: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description MusicBrainz release-group MBID */
                id: components["parameters"]["AlbumId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Album */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Album"];
                };
            };
            /** @description Invalid request */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Album not found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            405: components["responses"]["MethodNotAllowed"];
            /** @description Upstream error (MusicBrainz) */
            502: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Dependency unavailable */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
